from .packages import urllib3
from typing import Any

class HTTPError(Exception): ...
class ConnectTimeout(Exception): ...
class ConnectionError(Exception): ...

class Session:
    def get(
        self,url: str = "", proxies=None, verify=True, timeout=None, headers: Any = None
    ): ...
    def post(self,url: str = "", proxies=None, data=None, timeout=None, verify=True): ...

__all__ = ["get", "post"]
